# Generated by Django 5.2.4 on 2026-02-21 22:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_configbot_user_whatsappmessage_whatsappsession'),
    ]

    operations = [
        migrations.AddField(
            model_name='configbot',
            name='owner',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='config', to='app1.user'),
        ),
    ]
