# Generated by Django 5.2.4 on 2026-02-19 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app2', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfigBot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Nombre identificador del bot', max_length=150)),
                ('mensaje_bienvenida', models.CharField(blank=True, help_text='Mensaje de bienvenida al usuario', max_length=500)),
                ('instrucciones_ia', models.TextField(blank=True, help_text='Contexto o instrucciones para la IA / lógica de negocio')),
            ],
        ),
        migrations.CreateModel(
            name='WhatsAppSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qr_string', models.TextField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
