# Generated by Django 5.2.4 on 2026-02-19 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app2', '0003_whatsappmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='configbot',
            name='api_key',
            field=models.CharField(blank=True, help_text='API Key de DeepSeek', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='configbot',
            name='instrucciones_ia',
            field=models.TextField(blank=True, help_text='Prompt o instrucciones para la IA / lógica de negocio'),
        ),
    ]
