# Generated by Django 5.2.4 on 2026-02-21 21:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app2', '0004_configbot_api_key_alter_configbot_instrucciones_ia'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ConfigBot',
        ),
        migrations.DeleteModel(
            name='WhatsAppMessage',
        ),
        migrations.DeleteModel(
            name='WhatsAppSession',
        ),
    ]
